# Generated by Django 3.0.6 on 2020-06-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=90)),
                ('content', models.TextField(max_length=15000)),
                ('author', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
